#!/bin/bash

echo "================================"
echo "🎓 EDUCATION ONLINE PLATFORM"
echo "================================"
echo ""
echo "📋 Danh sách các lệnh hữu ích:"
echo ""
echo "🚀 KHỞI ĐỘNG HỆ THỐNG"
echo "   ./start.sh                 - Khởi động tất cả services"
echo "   docker-compose up -d       - Khởi động ở background"
echo ""
echo "📊 KIỂM TRA TRẠNG THÁI"
echo "   ./status.sh                - Xem trạng thái hệ thống"
echo "   docker-compose ps          - Xem containers đang chạy"
echo ""
echo "📝 XEM LOGS"
echo "   docker-compose logs -f                - Tất cả services"
echo "   docker-compose logs -f backend        - Chỉ backend"
echo "   docker-compose logs -f frontend       - Chỉ frontend"
echo "   docker-compose logs -f mongo-primary  - MongoDB"
echo ""
echo "🔄 RESTART"
echo "   ./restart.sh                          - Restart tất cả"
echo "   docker-compose restart backend        - Restart backend"
echo "   docker-compose restart frontend       - Restart frontend"
echo ""
echo "🛑 DỪNG HỆ THỐNG"
echo "   ./stop.sh                  - Dừng tất cả services"
echo "   docker-compose down        - Dừng và xóa containers"
echo "   docker-compose down -v     - Dừng và xóa volumes (⚠️ Mất data)"
echo ""
echo "🔨 BUILD LẠI"
echo "   docker-compose up -d --build          - Build và start lại"
echo "   docker-compose build backend          - Build chỉ backend"
echo "   docker-compose build frontend         - Build chỉ frontend"
echo ""
echo "🗄️ DATABASE"
echo "   docker exec -it mongo_primary mongosh -u admin -p admin123"
echo "   └─ Vào MongoDB shell"
echo ""
echo "   docker exec -it redis_cache redis-cli"
echo "   └─ Vào Redis CLI"
echo ""
echo "🔍 DEBUG"
echo "   docker exec -it education_backend bash    - Vào backend container"
echo "   docker exec -it education_frontend sh     - Vào frontend container"
echo ""
echo "📡 TRUY CẬP"
echo "   Frontend:  http://localhost:3000"
echo "   Backend:   http://localhost:5000"
echo "   MongoDB:   localhost:27017"
echo "   Redis:     localhost:6379"
echo ""
echo "📚 DOCUMENTATION"
echo "   README.md              - Tổng quan"
echo "   QUICK_START.md         - Hướng dẫn nhanh"
echo "   SETUP_GUIDE.md         - Hướng dẫn chi tiết"
echo "   API_DOCUMENTATION.md   - API reference"
echo "   PROJECT_STRUCTURE.md   - Cấu trúc project"
echo "   SUMMARY.md             - Tổng kết tính năng"
echo ""
echo "================================"
